### ISSUE TITLE
IPNI Reverse Index for Retrieval Incentives

### ISSUE THREAD

**Issue by masih** [ipni/roadmap#1]
Description: Provide the ability to return a deterministic set of CIDs advertised by a given `providerID` for a given `ContextID`. 

ETA: 2023-10-31
Maintainer: @masih

```[tasklist]
### Milestones
- [ ] Design semantics of deterministic CID selection for a given random seed
- [ ] Implement the service
- [ ] Implement observability
- [ ] Deploy to Dev and test integration
- [ ] Production release
```

Known dependencies:
- Advertisement Mirroring

**Comment by xmcai2016** [comment]
Watch for updates in the https://github.com/ipni/xedni repo.

**Comment by bajtos** [comment]
Proposed specification of the new API endpoint: https://github.com/ipni/xedni/blob/master/openapi.yaml
